eugenius/wk06/d02/blog/config/routes.rb
# == Route Map
#
#       Prefix Verb   URI Pattern                  Controller#Action
#              GET    /                            posts#index
#        posts GET    /posts(.:format)             posts#index
#              POST   /posts(.:format)             posts#create
#     new_post GET    /posts/new(.:format)         posts#new
#    edit_post GET    /posts/:id/edit(.:format)    posts#edit
#         post GET    /posts/:id(.:format)         posts#show
#              PATCH  /posts/:id(.:format)         posts#update
#              PUT    /posts/:id(.:format)         posts#update
#              DELETE /posts/:id(.:format)         posts#destroy
#     comments GET    /comments(.:format)          comments#index
#              POST   /comments(.:format)          comments#create
#  new_comment GET    /comments/new(.:format)      comments#new
# edit_comment GET    /comments/:id/edit(.:format) comments#edit
#      comment GET    /comments/:id(.:format)      comments#show
#              PATCH  /comments/:id(.:format)      comments#update
#              PUT    /comments/:id(.:format)      comments#update
#              DELETE /comments/:id(.:format)      comments#destroy
#

Rails.application.routes.draw do
  get '/', to: "posts#index"
  # get '/post', to: "posts#show"
  # get '/posts/new', to: "posts#new"
  resources :posts
  resources :comments
end

eugenius/wk06/d02/blog/app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  author     :string(255)
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#  post_id    :integer
#

class Comment < ActiveRecord::Base
	belongs_to :post
end

eugenius/wk06/d02/blog/app/models/post.rb
class Post < ActiveRecord::Base
end

eugenius/wk06/d02/blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

eugenius/wk06/d02/blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def show
		@post = Post.find params[:id]
	end

	def new
		@post = Post.new
	end
end

eugenius/wk06/d02/blog/app/helpers/comments_helper.rb
module CommentsHelper
end

eugenius/wk06/d02/blog/app/helpers/posts_helper.rb
module PostsHelper
end

eugenius/wk06/d02/blog/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
<% end %>

eugenius/wk06/d02/blog/app/views/posts/index.html.erb
<% unless Post.count == 0 %>

	<% @posts.each do |post| %>
		<%= link_to post.title, post_path(post) %>
		<%= post.title %>
		<%= post.author %>
		<%= post.content %>
	<% end %>

<% else %>
	No blog posts found
<% end %>

<%#= link_to "Hello World", post_path %>
<!-- 
You need to wrap that link with some sort of validation that checks whether the post exists.

What I would suggest, is instead of doing it like this, use the each loop on line 3 to get the link -->

<!-- Apart from that - all your tests where sweet.  
 -->
<%= link_to "Add Post", new_post_path %>

eugenius/wk06/d02/blog/app/views/posts/show.html.erb
<%= @post.title %>
<br>
<%= @post.author %>
<br>
<%= @post.content %>
<br>
<% unless @post.comments.count == 0 %>
	<% @post.comments.each do |comment| %>
		<br>
		<%= comment.author %>
		<br>
		<%= comment.content %>
		<br>
	<% end %>
<% end %>