eugenius/wk07/d05/rails-stripe/config/routes.rb
Rails.application.routes.draw do
  resources :payments

end

eugenius/wk07/d05/rails-stripe/app/models/payment.rb
class Payment < ActiveRecord::Base
end

eugenius/wk07/d05/rails-stripe/app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @payments = Payment.all
    respond_with(@payments)
  end

  def show
    respond_with(@payment)
  end

  def new
    @payment = Payment.new
    respond_with(@payment)
  end

  def edit
  end

  def create
    @payment = Payment.new(payment_params)
    @payment.save
    respond_with(@payment)
  end

  def update
    @payment.update(payment_params)
    respond_with(@payment)
  end

  def destroy
    @payment.destroy
    respond_with(@payment)
  end

  private
    def set_payment
      @payment = Payment.find(params[:id])
    end

    def payment_params
      params[:payment]
    end
end

eugenius/wk07/d05/rails-stripe/app/helpers/payments_helper.rb
module PaymentsHelper
end

eugenius/wk07/d05/rails-stripe/app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

eugenius/wk07/d05/rails-stripe/app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

eugenius/wk07/d05/rails-stripe/app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Payments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

eugenius/wk07/d05/rails-stripe/app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

eugenius/wk07/d05/rails-stripe/app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>