eugenius/wk04/d02/Cook_book/config/routes.rb
# == Route Map
#
#          Prefix Verb   URI Pattern                     Controller#Action
#            root GET    /                               pages#index
#           books GET    /books(.:format)                books#index
#                 POST   /books(.:format)                books#create
#        new_book GET    /books/new(.:format)            books#new
#       edit_book GET    /books/:id/edit(.:format)       books#edit
#            book GET    /books/:id(.:format)            books#show
#                 PATCH  /books/:id(.:format)            books#update
#                 PUT    /books/:id(.:format)            books#update
#                 DELETE /books/:id(.:format)            books#destroy
#         recipes GET    /recipes(.:format)              recipes#index
#                 POST   /recipes(.:format)              recipes#create
#      new_recipe GET    /recipes/new(.:format)          recipes#new
#     edit_recipe GET    /recipes/:id/edit(.:format)     recipes#edit
#          recipe GET    /recipes/:id(.:format)          recipes#show
#                 PATCH  /recipes/:id(.:format)          recipes#update
#                 PUT    /recipes/:id(.:format)          recipes#update
#                 DELETE /recipes/:id(.:format)          recipes#destroy
#     ingredients GET    /ingredients(.:format)          ingredients#index
#                 POST   /ingredients(.:format)          ingredients#create
#  new_ingredient GET    /ingredients/new(.:format)      ingredients#new
# edit_ingredient GET    /ingredients/:id/edit(.:format) ingredients#edit
#      ingredient GET    /ingredients/:id(.:format)      ingredients#show
#                 PATCH  /ingredients/:id(.:format)      ingredients#update
#                 PUT    /ingredients/:id(.:format)      ingredients#update
#                 DELETE /ingredients/:id(.:format)      ingredients#destroy
#

Rails.application.routes.draw do
  get 'ingredients/index'

  get 'ingredients/show'

  get 'recipe/index'

  get 'books/index'

  root 'pages#index'
  resources :books
  resources :recipes
  resources :ingredients
end

eugenius/wk04/d02/Cook_book/app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  cuisine    :string(255)
#  chef       :string(255)
#  image      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Book < ActiveRecord::Base
	validates :title, presence: true
	validates :image, presence: true

	has_many :recipes
end

eugenius/wk04/d02/Cook_book/app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  measurement :string(255)
#  cost        :float
#  image       :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Ingredient < ActiveRecord::Base
	validates :name, 
						presence: true,
						uniqueness: true
	validates :measurement, presence: true
	validates :image, presence: true

	has_many :ingredients_recipes
	has_many :recipes, through: :ingredients_recipes	
end

eugenius/wk04/d02/Cook_book/app/models/ingredients_recipe.rb
# == Schema Information
#
# Table name: ingredients_recipes
#
#  id            :integer          not null, primary key
#  ingredient_id :integer
#  recipe_id     :integer
#  created_at    :datetime
#  updated_at    :datetime
#

class IngredientsRecipe < ActiveRecord::Base
	belongs_to :ingredient
	belongs_to :recipe
end

eugenius/wk04/d02/Cook_book/app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  course       :string(255)
#  cooktime     :string(255)
#  servingsize  :string(255)
#  instructions :string(255)
#  image        :string(255)
#  created_at   :datetime
#  updated_at   :datetime
#

class Recipe < ActiveRecord::Base
	validates :instructions, length: {
		minimum: 200
	}
	validates :name, presence: true
	validates :course, presence: true
	validates :image, presence: true

	belongs_to :book

	has_many :ingredients_recipes
	#We use the ingredients_recipe table to 'jump through' to the ingredients table
	has_many :ingredients, through: :ingredients_recipes
end

eugenius/wk04/d02/Cook_book/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update, :destroy]

  def index
  	@books = Book.all 
  end

  def new
  	@book = Book.new
  end

  def create
  	@book = Book.new(book_params)
  	if @book.save #If book saved correctly in the db
	  	redirect_to book_path(@book) #Redirect that @book's path
	  else 
	  	render :new #Else it will render the 'new.html.erb' view
	  end
  end

  def show
  end

  def edit
  end

  def update
  	if @book.update(book_params)
	  	redirect_to books_path  		  		
  	else
  		render :edit
  	end	
  end

  def destroy
  	redirect_to books_path
  end

  private
  
  def find_book
    @book = Book.find params[:id]    
  end

  def book_params
    params.require(:book).permit(:title,
   															 :cuisine, 
   															 :chef,
   															 :image
     														)
  end
end

eugenius/wk04/d02/Cook_book/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	before_action :find_ingredient, only: [:show, :edit, :update, :destroy] 

  def index
  	@ingredients = Ingredient.all
  end

	def new
		@ingredient = Ingredient.new
	end  

	def create
		@ingredient = Ingredient.new(ingredient_params)
		if @ingredient.save 
			redirect_to @ingredient
		else
			render "new"
		end	
	end

	def show
	end

	def edit
	end

	def update
		if @ingredient.update(ingredient_params)
			redirect_to ingredient_path
		else
			render "edit"
		end
	end	

	def destroy
		@ingredient.destroy
		redirect_to ingredients_path @ingredient
	end

	private

	def find_ingredient
		@ingredient = Ingredient.find params[:id]
	end

  def ingredient_params
    params.require(:ingredient).permit(:name,
   															 :measurement, 
   															 :cost,
   															 :image
     														)
  end 
end

eugenius/wk04/d02/Cook_book/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	
  end
end

eugenius/wk04/d02/Cook_book/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]

  def index
  	@recipes = Recipe.all 	
  end

  def new
  	@recipe = Recipe.new
  end

  def create 
  	@recipe = Recipe.new(recipe_params)
  	if @recipe.save
  		redirect_to recipe_path(@recipe)
  	else
  		render :new
  	end
  end

  def show 
  end

  def edit
  end

  def update
  	if @recipe.update(recipe_params)
  		redirect_to @recipe	#Same as recipe_path @recipe
  	else
  		render 'edit'
  	end	
  end

  def destroy
  	@recipe.destroy
  	redirect_to @recipe
  end

  private #Everything below this is only for us to use

  def find_recipe #before_action Will execute before every action
  	@recipe = Recipe.find params[:id]
  end

  def recipe_params
  	params.require(:recipe).permit(:name, :course, :cooktime, :servingsize, :instructions, :image, :book_id, {ingredient_ids: []})
  end
end

eugenius/wk04/d02/Cook_book/app/helpers/books_helper.rb
module BooksHelper
end

eugenius/wk04/d02/Cook_book/app/helpers/ingredients_helper.rb
module IngredientsHelper
end

eugenius/wk04/d02/Cook_book/app/helpers/recipe_helper.rb
module RecipeHelper
end

eugenius/wk04/d02/Cook_book/app/views/books/_form.html.erb
<% unless @book.errors.empty? %>
	<ul id="errors">
		<% @book.errors.full_messages.each do |error| %>
			<li><%= error %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for @book do |f| %>
	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>

	<div class="form-group">
		<%= f.label :cuisine %>
		<%= f.text_field :cuisine %>
	</div>

	<div class="form-group">
		<%= f.label :chef %>	
		<%= f.text_field :chef %>	
	</div>	

	<div class="form-group">
		<%= f.label :image %>	
		<%= f.text_field :image %>	
	</div>		

	<div class="form-group">
		<%= f.submit %>	
	</div>					
<% end %>

eugenius/wk04/d02/Cook_book/app/views/books/edit.html.erb
<h1>Editing <%= @book.title %></h1>
<%= render 'form' %>

eugenius/wk04/d02/Cook_book/app/views/books/index.html.erb
<%= link_to '+ Add Book', new_book_path %>

<hr>
<ul>
		<% @books.each do |book|  %>
		<li>
			<h2><%= link_to book.title, book %></h2>
			<p>by <%= book.chef %></p>
			<button><%= link_to 'Edit', edit_book_path(book) %></button>
			<button><%= link_to 'Destroy', book, method: :delete  %></button>	
		</li>	
		<% end %>
</ul>

eugenius/wk04/d02/Cook_book/app/views/books/new.html.erb
<h1>New Cook Book</h1>
<%= render 'form' %>

eugenius/wk04/d02/Cook_book/app/views/books/show.html.erb
<h2><%= @book.title %></h2><br>
<small><%= @book.cuisine %> food, by <%= @book.chef %></small>

<br><br>

<div><%= image_tag @book.image %></div>

<br><br>

<button>
	<%= link_to "Edit", edit_book_path(@book) %>
</button>
<button>
	<%= link_to "Destroy", @book, method: :destroy %>
</button>

eugenius/wk04/d02/Cook_book/app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :course %>
		<%= f.text_field :course %>
	</p>
	<p>
		<%= f.label :cooktime, 'Cook Time' %>
		<%= f.text_field :cooktime, :placeholder => '10 Hours' %>
	</p>	
	<p>
		<%= f.label :servingsize, 'Serving Size' %>
		<%= f.text_field :servingsize %>
	</p>		
	<p>
		<%= f.label :instructions %>
		<%= f.text_area :instructions %>
	</p>	
	<p>
		<%= f.label :image %>
		<%= f.text_field :image %>
	</p>
	<p>
		<%= f.label :book_id %>
		<%= f.collection_select :book_id, Book.all, :id, :title %>		
	</p>
	<p>
		<%= f.label :ingredient_ids %>
		<%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name %>
	</p>
	<p>
		<%= f.submit %>	
	</p>	
<% end %>

eugenius/wk04/d02/Cook_book/app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<%= render 'form' %>

eugenius/wk04/d02/Cook_book/app/views/recipes/index.html.erb
<%= link_to '+ New Recipe', new_recipe_path %>

<hr>
<ul>
		<% @recipes.each do |recipe|  %>
		<li>
			<h3><%= link_to recipe.name, recipe %></h3>
			<p><%= recipe.course %></p>
			<p><%= image_tag recipe.image %></p>
			<button><%= link_to 'Edit', edit_recipe_path(recipe) %></button>
			<button><%= link_to 'Destroy', recipe, method: :delete  %></button>	
		</li>	
		<hr>
		<% end %>
</ul>

eugenius/wk04/d02/Cook_book/app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<%= render 'form' %>

eugenius/wk04/d02/Cook_book/app/views/recipes/show.html.erb
<h2><%= @recipe.name %></h2>

<% if @recipe.book %>
	<h3>In Cookbook: <%= @recipe.book.title %></h3>
<% end %>	

<p><%= image_tag @recipe.image %></p>
<p>Course: <%= @recipe.course %></p>
<p>Cook Time: <%= @recipe.cooktime %></p>
<p>Serving Size: <%= @recipe.servingsize %></p>

<p>
	Ingredients: 
	<ul>
		<% @recipe.ingredients.each do |ingredient| %>
		<li>
			<%= ingredient.name %>
		</li>	
		<% end %>
	</ul>	
</p>
<p>
	Instructions: <%= @recipe.instructions %>
</p>

<p class="button">
	<%= link_to "Edit", edit_recipe_path(@recipe) %>
</p>
<p class="button">
	<%= link_to "Destory", @recipe, method: :destroy %>
</p>